version: "3.9"

services:
  # Django web application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - ./:/code
    command: sh ./entrypoint.sh

  # PostgreSQL database
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  nginx:
    build: ./nginx
    ports:
      - "81:80"
      - "443:443"
    restart: always
    volumes:
      - ./:/code
      - certbot:/etc/letsencrypt
      - certbot:/var/www/certbot
    env_file:
      - .env
    depends_on:
      - web

volumes:
  static:
  certbot:
  postgres_data:
