version: "3"

services:
  # Django web application
  web:
    container_name: django-nginx-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
    command: sh ./entrypoint.sh

  # PostgreSQL database
  db:
    image: postgres:14.1-alpine
    container_name: my-postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./:/code
      # - certbot:/etc/letsencrypt
      # - certbot:/var/www/certbot
    env_file:
      - .env
    depends_on:
      - web

volumes:
  static:
  # certbot:
  postgres_data:
