name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          # 3rd party variables.

          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          envkey_DATABASE_USER: ${{ secrets.DATABASE_USER }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          envkey_DEBUG: ${{ secrets.DEBUG }}
          envkey_SECRET: ${{ secrets.SECRET }}

          file_name: .env
          fail_on_empty: false

      - name: Build the Docker image
        run: |
          docker compose build
          docker compose run --rm web python manage.py makemigrations     
          docker compose run --rm web python manage.py migrate 
          docker compose run --rm web python manage.py collectstatic --no-input

  # test:
  #   runs-on: self-hosted
  #   needs:
  #     - build
  #   steps:
  #     - name: Run tests
  #       run: |
  #         docker compose run --rm web python manage.py test

  deploy:
    runs-on: self-hosted
    needs:
      - build
    steps:
      - name: Deploy
        run: |
          docker compose up -d --force-recreate --remove-orphans
